/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f06acd64-06b6-4b75-a5b7-96044fe4ccfe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XEZ0cbjXC",
    "aws_user_pools_web_client_id": "3sag76he4mnb90iqarj5o5il64",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://x6o6mhqatfeibaq4cydcr3dmnm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-d4nyy6kavvfyjoigjrlscbwpiq",
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "map4f031982-staging": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "map4f031982-staging"
            }
        }
    }
};


export default awsmobile;
